### ISSUE TITLE
List some of my browsers/integrations

### ISSUE THREAD

**Issue by DanNixon** [lexbailey/emf_schedule_browsers#1]
I've created a few things that interact with the schedule:

- [A CLI](https://github.com/DanNixon/emfcamp-schedule-api/tree/main/cli), definitely works on Linux, should work on macOS and Windows too but untested.
- [A phone system integration](https://github.com/DanNixon/emfcamp-dial-a-schedule) on number 7243 (SCHD/SCHE) (possibly stretching the term "browser")
- [DAPNET/POCSAG announcements for pagers](https://github.com/DanNixon/emfcamp-dapnet-schedule-announcer/) (definitely stretching the term "browser")

**Comment by lexbailey** [comment]
Awesome! I'll have a look at these and figure out how best to list them :)
Thanks

**Comment by lexbailey** [comment]
Heheh, these are the first ones listed without screenshots, had to fix some CSS to make them look nice :sweat_smile: 

Anyway, these are live now! :partying_face: thanks for contributing

**Comment by DanNixon** [comment]
Cool, cheers!

In hindsight, I really should have dug out a photo of my pager displaying something from last EMF...

**Comment by lexbailey** [comment]
oo yeah, photos would be good. If you still want to I'm happy to add a photo :)

**Comment by DanNixon** [comment]
Took some digging, but managed to find one from 2022.

![IMG_20240529_143943_301](https://github.com/lexbailey/emf_schedule_browsers/assets/4037377/d3bf8be8-906d-4ca2-9383-13b7ff4a255f)

**Comment by lexbailey** [comment]
Added! Thanks :)
